name: Build Shizuku (Fixed)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '25.1.8937393'
          cmake-version: '3.22.1'

      - name: Generate debug keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore debug.keystore \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname 'CN=Android Debug,O=Android,C=US'
          mkdir -p ~/.android
          mv debug.keystore ~/.android/

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug \
            --no-daemon \
            --stacktrace \
            --warning-mode none \
            -Pandroid.injected.signing.store.file=$HOME/.android/debug.keystore \
            -Pandroid.injected.signing.store.password=android \
            -Pandroid.injected.signing.key.alias=androiddebugkey \
            -Pandroid.injected.signing.key.password=android

      - name: Collect outputs
        run: |
          mkdir -p artifacts
          find . -name '*.apk' -exec cp {} artifacts/ \;
          find . -name 'shizuku_server' -exec cp {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: shizuku-build-${{ github.run_number }}
          path: artifacts/*
          retention-days: 7
